groups:
- name: All
  jobs:
  - test_plr_light_centos7
  - test_plr_light_rhel8
  - test_plr_light_ubuntu18
  - greenplumR_release

resource_types:
    - name: terraform
      type: registry-image
      source:
        repository: ljfranklin/terraform-resource
        tag: 0.11.14
    - name: gcs
      type: registry-image
      source:
        repository: frodenas/gcs-resource

resources:
# Image Resources
- name: centos-gpdb-dev-7
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb5-centos7-build-test
    tag: latest

- name: ubuntu18-image-test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-test
    tag: latest

# Github Source Codes
- name: gpdb_src
  type: git
  source:
    branch: 6X_STABLE
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: GreenplumR_src
  type: git
  source:
    branch: sa/6X_rhel8
    uri: https://github.com/greenplum-db/GreenplumR.git

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_rhel8
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_rhel8/bin_gpdb.tar.gz

- name: bin_gpdb_ubuntu18
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz

- name: bin_plr_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: plr/published/gpdb6/plr-rhel7.gppkg

- name: bin_plr_ubuntu18
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: plr/published/gpdb6/plr-ubuntu18.gppkg

- name: bin_plr_rhel8
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: plr/published/gpdb6/plr-rhel8.gppkg

- name: rhel-image-dev-8
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb6-rhel8-test
    tag: latest
    username: _json_key
    password: ((container-registry-readonly-service-account-key))


- name: greenplumR-release
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: pl-analysis-suite/released/gpdb6/greenplumR-(.*).tar.gz

jobs:
- name: test_plr_light_centos7
  plan:
  - aggregate:
    - get: gpdb_src
    - get: GreenplumR_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: bin_plr
      resource: bin_plr_centos7
    - get: centos-gpdb-dev-7
  - task: test_greenplumr_plr_centos7
    file: GreenplumR_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-7
    params:

- name: test_plr_light_ubuntu18
  plan:
  - aggregate:
    - get: gpdb_src
    - get: GreenplumR_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
    - get: bin_plr
      resource: bin_plr_ubuntu18
    - get: ubuntu18-image-test
  - task: test_greenplumr_plr
    file: GreenplumR_src/concourse/tasks/test_plr.yml
    image: ubuntu18-image-test
    params:

- name: test_plr_light_rhel8
  plan:
  - aggregate:
    - get: gpdb_src
    - get: GreenplumR_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_rhel8
    - get: bin_plr
      resource: bin_plr_rhel8
    - get: rhel-image-dev-8
  - task: test_greenplumr_plr_rhel8
    file: GreenplumR_src/concourse/tasks/test_plr.yml
    image: rhel-image-dev-8
    params:

# Release GreenplumR GP Package
- name: greenplumR_release
  max_in_flight: 1
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: GreenplumR_src
  - task: plcontainer_gpdb_build
    file: GreenplumR_src/concourse/tasks/greenplumr_release.yml
    image: centos-gpdb-dev-7
  - aggregate:
    - put: greenplumR-release
      params:
        file: greenplumR-release/greenplumR-*.tar.gz
